### PR TITLE
Allow nonce to be set for debugbar_body

### PR DESCRIPTION
**Pull request by trevorrjohn**
Allow nonce to be set for content security policies

### CODE REVIEW

**Comment by trevorrjohn** [comment]
@julienbourdeau any thoughts on this?

**Comment by trevorrjohn** [comment]
Hey @julienbourdeau just wanted to ask again if you had any questions or feedback on this change.

**Comment by julienbourdeau** [comment]
Hi @trevorrjohn 
I'm really sorry for the delay. I don't see any reason not to merge it. I'll merge and release it this weekend 🙏

**Comment by trevorrjohn** [comment]
Hey @julienbourdeau sorry to bother again. I know you have a lot going on, but I didn't want this to get dropped.

**Comment by julienbourdeau** [comment]
Hey @trevorrjohn Sorry again for the delay!
I just published 0.3.3 with this fix https://github.com/julienbourdeau/debugbar/commit/6df7e2ebfda55b529f59e22e36bafdfc9adbc945

**Comment by pas256** [comment]
@trevorrjohn What did you have to do to get the nonce set? I might be doing something wrong, but what I see is:

```
<script type="text/javascript" data-turbo-permanent nonce="">
  window._debugbarConfigOptions = {"cable":{"url":"...
</script>
```

**Pull request merged**
